name: Build and Push Agent Image
on:
  pull_request:
  push:
    branches: [ortege]
    tags:
      - '**'

concurrency:
  group: build-push-agents-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-push:
    if: "! contains(toJSON(github.event.commits.*.message), '[skip-action]')"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # build_preset: ["dev", "lean", "py310", "websocket", "dockerize"]
        build_preset: ["dev", "lean", "dockerize"]
        platform: ["linux/amd64"]
      fail-fast: false
    steps:
      - name: "Checkout ${{ github.ref }} ( ${{ github.sha }} )"
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log into registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.CR_ENDPOINT }}
          username: ${{ secrets.CR_USERNAME }}
          password: ${{ secrets.CR_PASSWORD }}


      - name: Set container registry token
        if: github.event_name == 'push'
        run: |
          echo "DOCKERHUB_TOKEN=${{ secrets.CR_PASSWORD }}" >> $GITHUB_ENV


      - name: Build Docker Image
        shell: bash
        env:
          DOCKERHUB_USER: ${{ secrets.CR_USERNAME }}
          DOCKERHUB_REPO: ${{ secrets.CR_ENDPOINT }}/ortege/studio
        run: |
          pip install click
          ./scripts/build_docker.py ${{ matrix.build_preset }} ${{ github.event_name }} --platform ${{ matrix.platform }}
